version: '3.2'

services:
  alleventpictures-aacc:
    image: postgres:17
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin753951
      - POSTGRES_DB=AllEventPictures
    ports:
      - "5468:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped
    networks:
      - event-aacc-network

  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8081" # Expose port 8081 of the FastAPI app on port 8082 of the host
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://admin:admin753951@alleventpictures-aacc:5432/AllEventPictures
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    depends_on:
      - alleventpictures-aacc
      - redis
    restart: unless-stopped
    networks:
      - event-aacc-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - event-aacc-network

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A worker.celery_app worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://admin:admin753951@alleventpictures-aacc:5432/AllEventPictures
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    depends_on:
      - alleventpictures-aacc
      - redis
    restart: unless-stopped
    networks:
      - event-aacc-network

networks:
  event-aacc-network:
    driver: bridge
volumes:
  postgres_data:
