"""add_cart_id_to_transactions

Revision ID: 072947e71158
Revises: 2a79a78d7a50
Create Date: 2026-03-14 00:25:00.252008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '072947e71158'
down_revision: Union[str, Sequence[str], None] = '2a79a78d7a50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('cart_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'cart', ['cart_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'cart_id')
    # ### end Alembic commands ###
