"""add event_type limit joined_count to events

Revision ID: 1e2da4c9d201
Revises: 7ef447e714ef
Create Date: 2025-08-18 14:37:02.525680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e2da4c9d201'
down_revision: Union[str, Sequence[str], None] = '7ef447e714ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_type', sa.String(), nullable=False))
    op.add_column('events', sa.Column('limit', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('joined_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'joined_count')
    op.drop_column('events', 'limit')
    op.drop_column('events', 'event_type')
    # ### end Alembic commands ###
