"""add book bank and profile pic

Revision ID: 1ffe13be804b
Revises: 67f7b0e4f4f0
Create Date: 2026-01-06 22:26:20.595338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ffe13be804b'
down_revision: Union[str, Sequence[str], None] = '67f7b0e4f4f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('book_bank_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'book_bank_image')
    # ### end Alembic commands ###
