"""empty message

Revision ID: 2682d6f70d6e
Revises: 4e460a998f48
Create Date: 2025-09-06 21:55:50.847502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2682d6f70d6e'
down_revision: Union[str, Sequence[str], None] = '4e460a998f48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('downloaded', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'downloaded')
    # ### end Alembic commands ###
