"""empty message

Revision ID: 274fa3c71320
Revises: d9d633dc33d3
Create Date: 2025-09-03 22:29:44.906002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '274fa3c71320'
down_revision: Union[str, Sequence[str], None] = 'd9d633dc33d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart', 'created_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cart', 'updated_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_cart_session_id'), table_name='cart')
    op.drop_column('cart', 'session_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_cart_session_id'), 'cart', ['session_id'], unique=False)
    op.alter_column('cart', 'updated_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cart', 'created_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
