"""Add ondelete cascade

Revision ID: 52762b72f26a
Revises: ac9374dffd2f
Create Date: 2025-07-30 16:59:25.736698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52762b72f26a'
down_revision: Union[str, Sequence[str], None] = 'ac9374dffd2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('images_event_id_fkey'), 'images', type_='foreignkey')
    op.create_foreign_key(None, 'images', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.create_foreign_key(op.f('images_event_id_fkey'), 'images', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###
