"""create event table

Revision ID: 5a1e61b8357a
Revises: 7480d73b0911
Create Date: 2025-07-22 11:59:13.369755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a1e61b8357a'
down_revision: Union[str, Sequence[str], None] = '7480d73b0911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('users', sa.Column('updated_ad', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('users', 'update_ad')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('update_ad', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('users', 'updated_ad')
    op.alter_column('items', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
