"""add photograper's dashboard

Revision ID: 66241becfa38
Revises: 1ffe13be804b
Create Date: 2026-01-07 15:35:31.738651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66241becfa38'
down_revision: Union[str, Sequence[str], None] = '1ffe13be804b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('total_amount', sa.Integer(), nullable=True))
    op.add_column('cart', sa.Column('payment_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('cart', sa.Column('stripe_session_id', sa.String(), nullable=True))
    op.add_column('cart', sa.Column('photographer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cart', 'users', ['photographer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_column('cart', 'photographer_id')
    op.drop_column('cart', 'stripe_session_id')
    op.drop_column('cart', 'payment_date')
    op.drop_column('cart', 'total_amount')
    # ### end Alembic commands ###
