"""User migrations

Revision ID: 67cfd294015b
Revises: f6b0291e1f2e
Create Date: 2025-07-25 11:49:37.613983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67cfd294015b'
down_revision: Union[str, Sequence[str], None] = 'f6b0291e1f2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('created_by_id', sa.Integer(), nullable=False))
    op.add_column('events', sa.Column('updated_by_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'events', 'users', ['updated_by_id'], ['id'])
    op.create_foreign_key(None, 'events', 'users', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'updated_by_id')
    op.drop_column('events', 'created_by_id')
    # ### end Alembic commands ###
