"""Update model event

Revision ID: 69a8ed0ad0b2
Revises: c9328f8506d3
Create Date: 2025-07-25 15:56:32.020247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69a8ed0ad0b2'
down_revision: Union[str, Sequence[str], None] = 'c9328f8506d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('public_id', sa.String(), nullable=False))
    op.alter_column('events', 'image_cover',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_events_title'), table_name='events')
    op.create_index(op.f('ix_events_title'), 'events', ['title'], unique=False)
    op.create_index(op.f('ix_events_image_cover'), 'events', ['image_cover'], unique=False)
    op.create_index(op.f('ix_events_public_id'), 'events', ['public_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_public_id'), table_name='events')
    op.drop_index(op.f('ix_events_image_cover'), table_name='events')
    op.drop_index(op.f('ix_events_title'), table_name='events')
    op.create_index(op.f('ix_events_title'), 'events', ['title'], unique=True)
    op.alter_column('events', 'image_cover',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('events', 'public_id')
    # ### end Alembic commands ###
