"""migrate

Revision ID: 80386327cb27
Revises: c74bba9106df
Create Date: 2025-09-03 20:23:26.867945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80386327cb27'
down_revision: Union[str, Sequence[str], None] = 'c74bba9106df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('session_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_cart_session_id'), 'cart', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cart_session_id'), table_name='cart')
    op.drop_column('cart', 'session_id')
    # ### end Alembic commands ###
