"""add status to image

Revision ID: 8c0fb1719d87
Revises: bec380a03509
Create Date: 2026-03-07 17:23:43.987795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
"""add status to image

Revision ID: 8c0fb1719d87
Revises: bec380a03509
Create Date: 2026-03-07 17:23:43.987795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c0fb1719d87'
down_revision: Union[str, Sequence[str], None] = 'bec380a03509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('status', sa.String(), nullable=False, server_default='PENDING_AI'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'status')
    # ### end Alembic commands ###
