"""add date_of_birth

Revision ID: 9288361590e5
Revises: 94fb14741214
Create Date: 2026-01-15 19:04:46.889378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9288361590e5'
down_revision: Union[str, Sequence[str], None] = '94fb14741214'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bank_infos_id'), table_name='bank_infos')
    op.drop_table('bank_infos')
    op.add_column('users', sa.Column('date_of_birth', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'date_of_birth')
    op.create_table('bank_infos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bank_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bank_branch', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('account_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('account_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('citizen_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('bank_infos_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('bank_infos_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('bank_infos_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_bank_infos_id'), 'bank_infos', ['id'], unique=False)
    # ### end Alembic commands ###
