"""Add relation one2many event

Revision ID: ac9374dffd2f
Revises: c23e3a372881
Create Date: 2025-07-30 16:44:55.764702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac9374dffd2f'
down_revision: Union[str, Sequence[str], None] = 'c23e3a372881'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('event_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'images', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_column('images', 'event_id')
    # ### end Alembic commands ###
