"""remove age column from users

Revision ID: ae4456d49471
Revises: 66241becfa38
Create Date: 2026-01-09 11:04:03.801472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae4456d49471'
down_revision: Union[str, Sequence[str], None] = '66241becfa38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cart_photographer_id_fkey'), 'cart', type_='foreignkey')
    op.drop_column('cart', 'stripe_session_id')
    op.drop_column('cart', 'total_amount')
    op.drop_column('cart', 'payment_date')
    op.drop_column('cart', 'photographer_id')
    op.drop_column('users', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('cart', sa.Column('photographer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('cart', sa.Column('payment_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('cart', sa.Column('total_amount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('cart', sa.Column('stripe_session_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('cart_photographer_id_fkey'), 'cart', 'users', ['photographer_id'], ['id'])
    # ### end Alembic commands ###
