"""Remove images field assest_id

Revision ID: bbcb0991451f
Revises: 52762b72f26a
Create Date: 2025-08-01 11:53:50.987139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbcb0991451f'
down_revision: Union[str, Sequence[str], None] = '52762b72f26a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'assert_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('assert_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
