"""empty message

Revision ID: cd50f311170f
Revises: 274fa3c71320
Create Date: 2025-09-04 21:21:14.942098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd50f311170f'
down_revision: Union[str, Sequence[str], None] = '274fa3c71320'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cart_images_id'), table_name='cart_images')
    op.drop_table('cart_images')
    op.drop_constraint(op.f('images_cart_id_fkey'), 'images', type_='foreignkey')
    op.drop_column('images', 'cart_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('cart_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('images_cart_id_fkey'), 'images', 'cart', ['cart_id'], ['id'], ondelete='CASCADE')
    op.create_table('cart_images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cart_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], name=op.f('cart_images_cart_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['image_id'], ['cart.id'], name=op.f('cart_images_image_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('cart_images_pkey'))
    )
    op.create_index(op.f('ix_cart_images_id'), 'cart_images', ['id'], unique=False)
    # ### end Alembic commands ###
