"""empty message

Revision ID: d9d633dc33d3
Revises: 80386327cb27
Create Date: 2025-09-03 21:10:22.960137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9d633dc33d3'
down_revision: Union[str, Sequence[str], None] = '80386327cb27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart', 'session_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('cart', 'created_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cart', 'updated_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart', 'updated_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cart', 'created_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cart', 'session_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
