"""user and event migrations

Revision ID: f6b0291e1f2e
Revises: 5a1e61b8357a
Create Date: 2025-07-22 15:47:07.393645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6b0291e1f2e'
down_revision: Union[str, Sequence[str], None] = '5a1e61b8357a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('events', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('events', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('users', 'created_ad')
    op.drop_column('users', 'updated_ad')
    op.drop_column('users', 'deleted_ad')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deleted_ad', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('updated_ad', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('created_ad', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('events', 'deleted_at')
    op.drop_column('events', 'updated_at')
    op.drop_column('events', 'created_at')
    # ### end Alembic commands ###
